rvm:
  - 2.6.0
bundler_args: --without development

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database car_parked_api_test;' -U postgres
  - bundle exec rake db:drop db:create db:schema:load --trace

script:
  - RAILS_ENV=test bundle exec rspec

addons:
  postgresql: '9.5'
